### ISSUE TITLE
Boolean (flag) data types

### ISSUE THREAD

**Issue by l3nz** [l3nz/cli-matic#13]
I see a few boolean options:

- flags like `--flag` (true) or `--no-flag` (false). The first one could be shortened to `-f`
- flags with parameters, like `--flag=1`. Would expect to recognise "Y", "Yes", "On", "T", "True" and "1" as truthy. Falsey would be "N", "No", "Off", "F", "False" and "0". Other values would raise an error.

**Comment by wandersoncferreira** [comment]
hi @l3nz how are you?

I'm building a cli app for myself to handle my books (notes, registering, avg rating, prices I paid, etc) a very brief example can be seen here: https://asciinema.org/a/TYR5nUZunC3bs2OAFTIwp9ZOU


Therefore, I'm interested in implementing this functionality into the code-base because I really needed some of this in my project. I read the code very briefly and I could get a good grasp about the overall structure and design of the project.

Could you walk with me around this first issue? Do you already have something in mind about how to do it?

**Comment by WhittlesJr** [comment]
I'd love to have this!

**Comment by joshrotenberg** [comment]
I could use this too. I sort of got around it with:

```clojure
 {:option "new-hire" :short "nh" :type #{"true" "false"}}
```
and in the `fn` that runs this command I use `read-string` to parse it (and it's then handed off to a database insert statement).

For inspiration, there is a great Kotlin CLI handling library called clikt, and here are the docs for how it handles booleans:

https://ajalt.github.io/clikt/options/#boolean-flag-options

**Comment by Jeiwan** [comment]
Has there been any progress on this feature? I'd like to implement it.

**Comment by l3nz** [comment]
@Jeiwan go for it - I have not touched it because I thought it could be a good starting point for people willing to give it a try. 😺

**Comment by Jeiwan** [comment]
I have the first approach implemented and working. Now I'm working on the second approach and I have problems making both of them one type. I think it'll be better to have different types, for example `:flag` for the first approach and `:boolean` for the second one. `tools.cli` calls it "flag":
https://github.com/clojure/tools.cli/blob/3195c7e95fa7527fb0c74085418f44006e724863/src/main/clojure/clojure/tools/cli.cljc#L102-L103
There's actually no boolean type with argument description in `tools.cli`.

The problem with having one type is that we need to produce two `tools.cli` options  out of one `cli-matic` option. E.g. `{:option "flag" :as "flag" :type :boolean}` would produce:
```clj
["-f" "--flag B" "flag" :parse-fn P/parseBoolean]
```
And:
```clj
["-f" "--[no-]flag" "flag"]
```
The problem is that we cannot have two options with identical short and long names. Calling "--flag=0" (no matter what value actually) will always be `true` because it's treated as a flag. Prepending `--with-` looks unnatural. `tools.cli` doesn't support `--with-` and it would produce less readable options, like `--with-enable-feature` instead of simply `--enable-feature`.

Maybe the second approach is not necessary and excessive? Booleans have only two states, true or false, and flags fully cover these states. Ideally, the second approach shouldn't recognize anything but "true" or "false", which narrows down to a flag, naturally.

**Comment by l3nz** [comment]
I would create two different  "types", like `:flag` for `--flag=Y` and `:with-flag` for `--flag` / `--no-flag`. You may want one but  not both, and which one is a matter of personal preference.

**Comment by olymk2** [comment]
nice i was just looking for boolean params, hope to see this added soon :)

**Comment by Jeiwan** [comment]
I'll return to this next week!
